files:
  -
    source: /bb/**/*.md
    translation: /aa/**/%language%/%original_file_name%
  -
    source: /aa/**/*.*
    translation: /aa/**/%language%/%original_file_name%
    ignore: 
        - "/aa/1/README.md"
