files:
  -
    source: /bb/**/*.md
    translation: /%original_path%/%language%/%original_file_name%
  -
    source: /aa/**/*.*
    translation: /%original_path%/%language%/%original_file_name%
    ignore: 
        - /aa/1/README.md

