files:
  -      
    source: /**/*.* # translatable texts are stored in "text" nodes of parent node "content"
    translation: '/**/%two_letters_code%_%original_file_name%' # translatable texts are stored in "text" nodes of parent node "content"
    languages_mapping:
      two_letters_code:
        en: ru
        ua: ff
      tree_latters_code:
        sfa_SFA: un_uns
    ignore:
      - /**/*.txt

        
