files:
  - 
    source: '/**/*'
    ignore:
      - '/**/1.*'
    translation: '/%two_letters_code%/%original_path%/%original_file_name%'
    languages_mapping:
      two_letters_code:
        it: fdsa
    scheme: identifier,source_phrase,translation
