files:
  - 
    source: '/**/*.md'
    translation: '/**/%two_letters_code%_%original_file_name%'
  - 
    source: '/**/*.txt'
    ignore:
      - '**/1/'
    translation: '/**/%two_letters_code%-%original_file_name%'
