#simple comment

files:
#simple comment
  -             #simple comment
    source: /bb/**/*.md
    translation: /aa/**/%language%/%original_file_name%
  -
    source: /aa/**/*.*
    translation: /%language%/**/%original_file_name%  #simple comment
    ignore: #simple comment
        - /aa/1/README.md#simple comment
  - #simple comment
    source: /**/*.* ### #simple comment
    #simple comment
#simple comment
    translation: /%two_letters_code%/**/%original_file_name%   #simple comment
#simple comment
