files:
  -      
    source: /**/*.xml
    translation: /**/%two_letters_code%_%original_file_name%
    translatable_elements:
      - /content/text             # translatable texts are stored in "text" nodes of parent node "content"
