files:
  -
<<<<<<< HEAD
    source: /bb/**/*.md
=======
    source: /**/*.md
>>>>>>> 658620242aa1dfa00633c6fdb2ea1aedabe7a642
    translation: /%original_path%/%language%/%original_file_name%
  -
    source: /aa/**/*.*
    translation: /%original_path%/%language%/%original_file_name%
    ignore: 
        - /aa/1/README.md

