files:
  - 
    source: '/**/*.*'
    translation: "'/**/%two_letters_code%_%original_file_name%'"
    languages_mapping:
      two_letters_code:
        en: ru
        ua: ff
      tree_latters_code:
        sfa_SFA: un_uns
    ignore:
      - '/**/*.txt'
